In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,Imputer
from sklearn.metrics import accuracy_score
lbl=LabelEncoder()
df= pd.read_csv('game.csv')[0:4380]
X= df.iloc[:,0:4].values
Y= df.iloc[:,4:5].values
Y = lbl.fit_transform(Y)
#print(Y)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.4,random_state=0)
from sklearn.svm import SVC
cls= SVC(kernel= 'rbf',random_state=0,gamma=0.00011)
#print(X_train,y_train)
cls.fit(X_train,y_train)
Y_pred= cls.predict(X_test)
print(accuracy_score(y_test,Y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,Y_pred)
print(cm)

C:\Users\supratik chanda\Documents\New folder (2)\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7631278538812786
[[  0  88   0   0   3   0]
 [  0 581   0   0   8   0]
 [  0  97   0   0   6   0]
 [  0   0   0   0 105   0]
 [  0   0   0   0 756   0]
 [  0   0   0   0 108   0]]
